---
services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9-dld01-infra-services
    environment: 
         - BIND9_USER=root
         - TZ=Europe/Stockholm
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /etc/bind/:/etc/bind/
      - /var/cache/bind:/var/cache/bind
      - /var/lib/bind:/var/lib/bind
    restart: always